print("WELCOME")
print("Choose the Element to get its Atomic Number \a")
print("C\t" , "I\t","B\t","Hg\t","Ag\t","Au\t","Ca\t","Zn\t","Pt\t","Pb\t","Cl\t","K\t","Al\t","Fe\t","Cu\t","Na\t","H\t","He\n","Li\t","P\t","S\t","Sn\t","Si\t","Ni\t","Ar\t","Br\t","Co\t","Mg\t","Mn\t","F\t",)
name = input("Write same as it is given above \n")
if name == ("C"):
    print("Atomic Number of" , name , "is----> 6")
elif name == ("I"):
    print("Atomic Number of" , name , "is----> 53")
elif name == ("B"):
    print("Atomic Number of" , name , "is----> 5")
elif name == ("Hg"):
    print("Atomic Number of" , name , "is----> 80")
elif name == ("Ag"):
    print("Atomic Number of" , name , "is----> 47")
elif name == ("Au"):
    print("Atomic Number of" , name , "is----> 79")
elif name == ("Ca"):
    print("Atomic Number of" , name , "is----> 20")
elif name == ("Zn"):
    print("Atomic Number of" , name , "is----> 30")
elif name == ("Pt"):
    print("Atomic Number of" , name , "is----> 78")
elif name == ("Pb"):
    print("Atomic Number of" , name , "is----> 82")
elif name == ("Cl"):
    print("Atomic Number of" , name , "is----> 17")
elif name == ("K"):
    print("Atomic Number of" , name , "is----> 19")
elif name == ("Al"):
    print("Atomic Number of" , name , "is----> 13")
elif name == ("Fe"):
    print("Atomic Number of" , name , "is----> 26")
elif name == ("Cu"):
    print("Atomic Number of" , name , "is----> 29")
elif name == ("Na"):
    print("Atomic Number of" , name , "is----> 11")
elif name == ("H"):
    print("Atomic Number of" , name , "is----> 1")
elif name == ("He"):
    print("Atomic Number of" , name , "is----> 2")
elif name == ("Li"):
    print("Atomic Number of" , name , "is----> 3")
elif name == ("P"):
    print("Atomic Number of" , name , "is----> 15")
elif name == ("S"):
    print("Atomic Number of" , name , "is----> 16")
elif name == ("Sn"):
    print("Atomic Number of" , name , "is----> 50")
elif name == ("Si"):
    print("Atomic Number of" , name , "is----> 14")
elif name == ("Ni"):
    print("Atomic Number of" , name , "is----> 28")
elif name == ("Ar"):
    print("Atomic Number of" , name , "is----> 18")
elif name == ("Br"):
    print("Atomic Number of" , name , "is----> 35")
elif name == ("Co"):
    print("Atomic Number of" , name , "is----> 27")
elif name == ("Mg"):
    print("Atomic Number of" , name , "is----> 12")
elif name == ("Mn"):
    print("Atomic Number of" , name , "is----> 25")
elif name == ("F"):
    print("Atomic Number of" , name , "is----> 9")
else:
    print("Error! Please Check Your Input!")
















